ARRAY OPERATIONS

In [3]:
import numpy as np

In [4]:
arr1 =  np.array([1,2,3,4,5,6])

In [6]:
arr2 =  np.array([7,8,9,10,11,12])

In [7]:
arr1 + arr2 

array([ 8, 10, 12, 14, 16, 18])

In [8]:
arr1 - arr2

array([-6, -6, -6, -6, -6, -6])

In [9]:
arr1 * arr2

array([ 7, 16, 27, 40, 55, 72])

In [10]:
arr1/arr2

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [11]:
arr1//arr2

array([0, 0, 0, 0, 0, 0])

In [12]:
arr1 ** arr2

array([         1,        256,      19683,    1048576,   48828125,
       2176782336])