ARRAY INDEXING AND SLICING

In [1]:
import numpy as np

In [2]:
arr =  np.arange(11,21)

In [3]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[9]

np.int64(20)

In [5]:
arr[4]

np.int64(15)

SLICING 

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [9]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [10]:
arr = np.arange(1,31).reshape(6,5)

In [11]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5])

In [13]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [14]:
arr[1,2]

np.int64(8)

In [15]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

rows and columns slicing

In [19]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

    BOOLEAN INDEXING 

In [21]:
arr =  np.arange(11,21)

In [22]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
bool_index = arr % 2 == 0

In [24]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
arr =  arr[bool_index]

In [26]:
arr

array([12, 14, 16, 18, 20])