ARRAY OPERATIONS

In [1]:
import numpy as np

In [4]:
arr1 =  np.array([1,2,3,4,5,6])

In [6]:
arr2 =  np.array([7,8,9,10,11,12])

In [7]:
arr1 + arr2 

array([ 8, 10, 12, 14, 16, 18])

In [8]:
arr1 - arr2

array([-6, -6, -6, -6, -6, -6])

In [9]:
arr1 * arr2

array([ 7, 16, 27, 40, 55, 72])

In [10]:
arr1/arr2

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [11]:
arr1//arr2

array([0, 0, 0, 0, 0, 0])

In [12]:
arr1 ** arr2

array([         1,        256,      19683,    1048576,   48828125,
       2176782336])

BROADCASTING

In [2]:
l = [10,20,30,40]
arr = np.array(l)

In [3]:
arr + 10 

array([20, 30, 40, 50])

In [4]:
arr2 = np.arange(1,26).reshape(5,5)

In [5]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
arr2 * 10 

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

DEEP AND SHALLOW COPY


In [8]:
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [9]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [10]:
slice + 5 

array([ 6,  7,  8,  9, 10])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

deep copy 

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [14]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [15]:
b[0] = 99

In [16]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
c = a.copy()
c

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [18]:
c[1] = 22

In [19]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
c

array([99, 22,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

MATRIX OPERATIONS

In [26]:
k = np.array([[1,2],[3,4]])
k

array([[1, 2],
       [3, 4]])

In [25]:
l = np.array([[5,6],[7,8]])
l

array([[5, 6],
       [7, 8]])

In [27]:
k @ l

array([[19, 22],
       [43, 50]])

In [28]:
np.dot(k,l)

array([[19, 22],
       [43, 50]])

In [31]:
k.T

array([[1, 3],
       [2, 4]])

        ADVANCED ARRAY MANIPULATION

STACKING 

In [32]:
a = np.array([1,2,3,4,5])

In [33]:
b = np.array([6,7,8,9,10])

In [34]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

SPLITTING ARRAY

In [38]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.split(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [40]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [41]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [42]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]