In [3]:
import numpy as np

basic array creation 

In [ ]:
arr = np.array([1,2,3,4,5,6])

In [5]:
print(arr)

[1 2 3 4 5 6]


In [7]:
l = [[1,2,3,3,4],[33,4,6,7,8],[3,2,1,55,6]]

In [8]:
print(l)

[[1, 2, 3, 3, 4], [33, 4, 6, 7, 8], [3, 2, 1, 55, 6]]


In [9]:
np.array(l)

array([[ 1,  2,  3,  3,  4],
       [33,  4,  6,  7,  8],
       [ 3,  2,  1, 55,  6]])

ARRAY GENERATION

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr =  np.zeros(6)

In [9]:
print(arr)

[0. 0. 0. 0. 0. 0.]


In [12]:
ar = np.zeros((6,6))

In [13]:
print(ar)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
